In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [80]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Projects/zomato_analytics_dataset.csv')

In [81]:
df.head()

,Order_ID,Customer_ID,Restaurant_Name,City,Cuisine_Type,Dish_Name,Order_Date,Order_Time,Order_Status,Delivery_Duration_Minutes,Payment_Method,Order_Value,Discount_Applied,Customer_Rating,Delivery_Partner_ID,Delivery_Partner_Rating,Cancellation_Reason,Is_First_Order,Restaurant_Rating,Tip_Amount
0,ORD00001,CUST5824,"Becker, Dorsey and Nunez",Bangalore,Chinese,Nature,18-09-2024,18:46:00,Delivered,87.0,Cash,665.60,Yes,3.1,DP249,3.2,NaN,No,4.9,53.12
1,ORD00002,CUST8654,Kim-Hunter,Kolkata,Continental,Evidence,02-07-2024,18:01:41,Delivered,61.0,UPI,986.56,Yes,NaN,DP369,NaN,NaN,Yes,4.8,99.47
2,ORD00003,CUST1015,Powell Inc,Delhi,Chinese,Among,21-05-2024,12:02:54,Cancelled,NaN,Wallet,799.55,Yes,NaN,DP569,NaN,Restaurant Unavailable,Yes,3.3,0.00
3,ORD00004,CUST5784,West-Schneider,Kolkata,Thai,He,31-01-2025,02:59:17,Delivered,25.0,UPI,875.85,No,NaN,DP295,2.3,NaN,No,4.1,67.67
4,ORD00005,CUST5540,Patel LLC,Chennai,South Indian,Year,02-11-2024,22:32:50,Delivered,68.0,Cash,775.78,Yes,4.2,DP968,4.3,NaN,No,4.5,35.30

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Order_ID                   10000 non-null  object
 1   Customer_ID                10000 non-null  object
 2   Restaurant_Name            10000 non-null  object
 3   City                       10000 non-null  object
 4   Cuisine_Type               10000 non-null  object
 5   Dish_Name                  9993 non-null   object
 6   Order_Date                 10000 non-null  object
 7   Order_Time                 10000 non-null  object
 8   Order_Status               10000 non-null  object
 9   Delivery_Duration_Minutes  7964 non-null   float64
 10  Payment_Method             10000 non-null  object
 11  Order_Value                10000 non-null  float64
 12  Discount_Applied           10000 non-null  object
 13  Customer_Rating            3947 non-null   float64
 14  Delivery_Partner_ID        10000 non-null  object
 15  Delivery_Partner_Rating    3938 non-null   float64
 16  Cancellation_Reason        1629 non-null   object
 17  Is_First_Order             10000 non-null  object
 18  Restaurant_Rating          10000 non-null  float64
 19  Tip_Amount                 10000 non-null  float64
dtypes: float64(6), object(14)
memory usage: 1.5+ MB

In [83]:
df.describe()

,Delivery_Duration_Minutes,Order_Value,Customer_Rating,Delivery_Partner_Rating,Restaurant_Rating,Tip_Amount
count,7964.000000,10000.000000,3947.000000,3938.000000,10000.000000,10000.000000
mean,55.036288,551.122908,2.986572,2.977476,4.009810,40.126607
std,20.328776,261.115222,1.152453,1.165457,0.580483,32.667671
min,20.000000,100.050000,1.000000,1.000000,3.000000,0.000000
25%,37.000000,325.330000,2.000000,2.000000,3.500000,6.237500
50%,55.000000,551.585000,3.000000,3.000000,4.000000,37.720000
75%,73.000000,779.940000,4.000000,4.000000,4.500000,68.960000
max,90.000000,999.990000,5.000000,5.000000,5.000000,100.000000

In [84]:
df.isna().sum()

Order_ID                        0
Customer_ID                     0
Restaurant_Name                 0
City                            0
Cuisine_Type                    0
Dish_Name                       7
Order_Date                      0
Order_Time                      0
Order_Status                    0
Delivery_Duration_Minutes    2036
Payment_Method                  0
Order_Value                     0
Discount_Applied                0
Customer_Rating              6053
Delivery_Partner_ID             0
Delivery_Partner_Rating      6062
Cancellation_Reason          8371
Is_First_Order                  0
Restaurant_Rating               0
Tip_Amount                      0
dtype: int64

In [85]:
df['Delivery_Duration_Minutes'].value_counts()

Delivery_Duration_Minutes
32.0    143
35.0    134
76.0    133
58.0    131
61.0    130
       ...
87.0     96
71.0     94
38.0     93
56.0     91
45.0     89
Name: count, Length: 71, dtype: int64

In [86]:
df['Delivery_Duration_Minutes'].mean()

np.float64(55.03628829733802)

In [87]:
df['Delivery_Duration_Minutes'].fillna(df['Delivery_Duration_Minutes'].mean(), inplace=True)

<ipython-input-87-27105695a42c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Delivery_Duration_Minutes'].fillna(df['Delivery_Duration_Minutes'].mean(), inplace=True)

In [88]:
df['Delivery_Duration_Minutes'].mean()

np.float64(55.036288297338025)

In [89]:
df.isna().sum()

Order_ID                        0
Customer_ID                     0
Restaurant_Name                 0
City                            0
Cuisine_Type                    0
Dish_Name                       7
Order_Date                      0
Order_Time                      0
Order_Status                    0
Delivery_Duration_Minutes       0
Payment_Method                  0
Order_Value                     0
Discount_Applied                0
Customer_Rating              6053
Delivery_Partner_ID             0
Delivery_Partner_Rating      6062
Cancellation_Reason          8371
Is_First_Order                  0
Restaurant_Rating               0
Tip_Amount                      0
dtype: int64

In [90]:
df['Cancellation_Reason'].fillna('Not Cancelled', inplace=True)

<ipython-input-90-52ad2fcdea9c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cancellation_Reason'].fillna('Not Cancelled', inplace=True)

In [91]:
df['Cancellation_Reason'].value_counts()

Cancellation_Reason
Not Cancelled               8371
Delivery Partner No Show     420
Restaurant Unavailable       418
Customer Cancelled           403
Other                        388
Name: count, dtype: int64

In [92]:
df['Customer_Rating'].mean()

np.float64(2.9865720800608053)

In [93]:
df['Customer_Rating'].fillna(df['Customer_Rating'].mean(), inplace=True)

<ipython-input-93-005ba09dc10a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Rating'].fillna(df['Customer_Rating'].mean(), inplace=True)

In [94]:
df['Customer_Rating'].mean()

np.float64(2.9865720800608053)

In [95]:
df['Customer_Rating']

0       3.100000
1       2.986572
2       2.986572
3       2.986572
4       4.200000
          ...
9995    2.986572
9996    2.900000
9997    2.986572
9998    2.986572
9999    4.400000
Name: Customer_Rating, Length: 10000, dtype: float64

In [96]:
df.describe()

,Delivery_Duration_Minutes,Order_Value,Customer_Rating,Delivery_Partner_Rating,Restaurant_Rating,Tip_Amount
count,10000.000000,10000.000000,10000.000000,3938.000000,10000.000000,10000.000000
mean,55.036288,551.122908,2.986572,2.977476,4.009810,40.126607
std,18.141421,261.115222,0.723975,1.165457,0.580483,32.667671
min,20.000000,100.050000,1.000000,1.000000,3.000000,0.000000
25%,42.000000,325.330000,2.986572,2.000000,3.500000,6.237500
50%,55.036288,551.585000,2.986572,3.000000,4.000000,37.720000
75%,68.000000,779.940000,2.986572,4.000000,4.500000,68.960000
max,90.000000,999.990000,5.000000,5.000000,5.000000,100.000000

In [97]:
df.head()

,Order_ID,Customer_ID,Restaurant_Name,City,Cuisine_Type,Dish_Name,Order_Date,Order_Time,Order_Status,Delivery_Duration_Minutes,Payment_Method,Order_Value,Discount_Applied,Customer_Rating,Delivery_Partner_ID,Delivery_Partner_Rating,Cancellation_Reason,Is_First_Order,Restaurant_Rating,Tip_Amount
0,ORD00001,CUST5824,"Becker, Dorsey and Nunez",Bangalore,Chinese,Nature,18-09-2024,18:46:00,Delivered,87.000000,Cash,665.60,Yes,3.100000,DP249,3.2,Not Cancelled,No,4.9,53.12
1,ORD00002,CUST8654,Kim-Hunter,Kolkata,Continental,Evidence,02-07-2024,18:01:41,Delivered,61.000000,UPI,986.56,Yes,2.986572,DP369,NaN,Not Cancelled,Yes,4.8,99.47
2,ORD00003,CUST1015,Powell Inc,Delhi,Chinese,Among,21-05-2024,12:02:54,Cancelled,55.036288,Wallet,799.55,Yes,2.986572,DP569,NaN,Restaurant Unavailable,Yes,3.3,0.00
3,ORD00004,CUST5784,West-Schneider,Kolkata,Thai,He,31-01-2025,02:59:17,Delivered,25.000000,UPI,875.85,No,2.986572,DP295,2.3,Not Cancelled,No,4.1,67.67
4,ORD00005,CUST5540,Patel LLC,Chennai,South Indian,Year,02-11-2024,22:32:50,Delivered,68.000000,Cash,775.78,Yes,4.200000,DP968,4.3,Not Cancelled,No,4.5,35.30

In [98]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

<ipython-input-98-422bc60de3cd>:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Order_ID                   10000 non-null  object
 1   Customer_ID                10000 non-null  object
 2   Restaurant_Name            10000 non-null  object
 3   City                       10000 non-null  object
 4   Cuisine_Type               10000 non-null  object
 5   Dish_Name                  9993 non-null   object
 6   Order_Date                 10000 non-null  datetime64[ns]
 7   Order_Time                 10000 non-null  object
 8   Order_Status               10000 non-null  object
 9   Delivery_Duration_Minutes  10000 non-null  float64
 10  Payment_Method             10000 non-null  object
 11  Order_Value                10000 non-null  float64
 12  Discount_Applied           10000 non-null  object
 13  Customer_Rating            10000 non-null  float64
 14  Delivery_Partner_ID        10000 non-null  object
 15  Delivery_Partner_Rating    3938 non-null   float64
 16  Cancellation_Reason        10000 non-null  object
 17  Is_First_Order             10000 non-null  object
 18  Restaurant_Rating          10000 non-null  float64
 19  Tip_Amount                 10000 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(13)
memory usage: 1.5+ MB

In [100]:
df.head(10)

,Order_ID,Customer_ID,Restaurant_Name,City,Cuisine_Type,Dish_Name,Order_Date,Order_Time,Order_Status,Delivery_Duration_Minutes,Payment_Method,Order_Value,Discount_Applied,Customer_Rating,Delivery_Partner_ID,Delivery_Partner_Rating,Cancellation_Reason,Is_First_Order,Restaurant_Rating,Tip_Amount
0,ORD00001,CUST5824,"Becker, Dorsey and Nunez",Bangalore,Chinese,Nature,2024-09-18,18:46:00,Delivered,87.000000,Cash,665.60,Yes,3.100000,DP249,3.2,Not Cancelled,No,4.9,53.12
1,ORD00002,CUST8654,Kim-Hunter,Kolkata,Continental,Evidence,2024-07-02,18:01:41,Delivered,61.000000,UPI,986.56,Yes,2.986572,DP369,NaN,Not Cancelled,Yes,4.8,99.47
2,ORD00003,CUST1015,Powell Inc,Delhi,Chinese,Among,2024-05-21,12:02:54,Cancelled,55.036288,Wallet,799.55,Yes,2.986572,DP569,NaN,Restaurant Unavailable,Yes,3.3,0.00
3,ORD00004,CUST5784,West-Schneider,Kolkata,Thai,He,2025-01-31,02:59:17,Delivered,25.000000,UPI,875.85,No,2.986572,DP295,2.3,Not Cancelled,No,4.1,67.67
4,ORD00005,CUST5540,Patel LLC,Chennai,South Indian,Year,2024-11-02,22:32:50,Delivered,68.000000,Cash,775.78,Yes,4.200000,DP968,4.3,Not Cancelled,No,4.5,35.30
5,ORD00006,CUST7944,Norman-Sims,Hyderabad,Italian,Hour,2024-12-18,02:37:27,Cancelled,55.036288,Card,179.97,No,2.986572,DP720,NaN,Restaurant Unavailable,Yes,4.9,0.00
6,ORD00007,CUST4713,Lopez and Sons,Pune,Thai,Different,2024-10-10,07:31:44,Delivered,52.000000,Wallet,223.87,Yes,2.986572,DP884,NaN,Not Cancelled,Yes,3.6,36.71
7,ORD00008,CUST3423,Goodwin LLC,Bangalore,Thai,Ability,2024-09-10,11:04:25,Delivered,82.000000,Wallet,598.39,No,2.986572,DP327,1.5,Not Cancelled,Yes,3.0,91.85
8,ORD00009,CUST1235,Thompson Group,Chennai,Continental,Resource,2024-09-02,11:45:43,Delivered,69.000000,UPI,976.54,No,2.600000,DP846,NaN,Not Cancelled,No,3.8,33.37
9,ORD00010,CUST8019,"Landry, Castillo and Myers",Bangalore,Italian,Eye,2025-03-09,06:45:04,Incomplete,55.036288,Card,761.00,No,2.986572,DP420,NaN,Restaurant Unavailable,No,4.9,0.00

In [101]:
df.isna().sum()

Order_ID                        0
Customer_ID                     0
Restaurant_Name                 0
City                            0
Cuisine_Type                    0
Dish_Name                       7
Order_Date                      0
Order_Time                      0
Order_Status                    0
Delivery_Duration_Minutes       0
Payment_Method                  0
Order_Value                     0
Discount_Applied                0
Customer_Rating                 0
Delivery_Partner_ID             0
Delivery_Partner_Rating      6062
Cancellation_Reason             0
Is_First_Order                  0
Restaurant_Rating               0
Tip_Amount                      0
dtype: int64

In [102]:
df.dropna(subset=['Dish_Name'], inplace=True)

In [103]:
df.shape

(9993, 20)

In [104]:
df.isna().sum()

Order_ID                        0
Customer_ID                     0
Restaurant_Name                 0
City                            0
Cuisine_Type                    0
Dish_Name                       0
Order_Date                      0
Order_Time                      0
Order_Status                    0
Delivery_Duration_Minutes       0
Payment_Method                  0
Order_Value                     0
Discount_Applied                0
Customer_Rating                 0
Delivery_Partner_ID             0
Delivery_Partner_Rating      6056
Cancellation_Reason             0
Is_First_Order                  0
Restaurant_Rating               0
Tip_Amount                      0
dtype: int64

In [105]:
df

,Order_ID,Customer_ID,Restaurant_Name,City,Cuisine_Type,Dish_Name,Order_Date,Order_Time,Order_Status,Delivery_Duration_Minutes,Payment_Method,Order_Value,Discount_Applied,Customer_Rating,Delivery_Partner_ID,Delivery_Partner_Rating,Cancellation_Reason,Is_First_Order,Restaurant_Rating,Tip_Amount
0,ORD00001,CUST5824,"Becker, Dorsey and Nunez",Bangalore,Chinese,Nature,2024-09-18,18:46:00,Delivered,87.000000,Cash,665.60,Yes,3.100000,DP249,3.2,Not Cancelled,No,4.9,53.12
1,ORD00002,CUST8654,Kim-Hunter,Kolkata,Continental,Evidence,2024-07-02,18:01:41,Delivered,61.000000,UPI,986.56,Yes,2.986572,DP369,NaN,Not Cancelled,Yes,4.8,99.47
2,ORD00003,CUST1015,Powell Inc,Delhi,Chinese,Among,2024-05-21,12:02:54,Cancelled,55.036288,Wallet,799.55,Yes,2.986572,DP569,NaN,Restaurant Unavailable,Yes,3.3,0.00
3,ORD00004,CUST5784,West-Schneider,Kolkata,Thai,He,2025-01-31,02:59:17,Delivered,25.000000,UPI,875.85,No,2.986572,DP295,2.3,Not Cancelled,No,4.1,67.67
4,ORD00005,CUST5540,Patel LLC,Chennai,South Indian,Year,2024-11-02,22:32:50,Delivered,68.000000,Cash,775.78,Yes,4.200000,DP968,4.3,Not Cancelled,No,4.5,35.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD09996,CUST4855,Schwartz-Velez,Chennai,Chinese,Side,2025-04-02,18:55:09,Cancelled,55.036288,UPI,380.59,No,2.986572,DP106,NaN,Customer Cancelled,No,4.9,0.00
9996,ORD09997,CUST3874,"Paul, Johnson and Richardson",Pune,South Indian,Check,2024-09-07,12:45:41,Delivered,81.000000,Card,108.03,Yes,2.900000,DP376,NaN,Not Cancelled,Yes,4.6,66.62
9997,ORD09998,CUST7928,Jackson-Frank,Bangalore,Biryani,While,2025-03-14,18:47:57,Delivered,46.000000,Wallet,736.20,Yes,2.986572,DP585,NaN,Not Cancelled,No,5.0,72.68
9998,ORD09999,CUST4131,Smith Ltd,Kolkata,Continental,Ball,2025-02-01,23:53:14,Cancelled,55.036288,UPI,240.64,Yes,2.986572,DP494,NaN,Other,Yes,3.2,0.00
9999,ORD10000,CUST3804,Downs-Hull,Delhi,Biryani,Cause,2025-03-17,11:47:36,Delivered,65.000000,Wallet,879.02,Yes,4.400000,DP313,3.8,Not Cancelled,Yes,3.0,95.83

In [107]:
df.to_csv('Cleaned.csv', index=False)

In [108]:
clean = pd.read_csv('/content/Cleaned.csv')

In [109]:
clean

,Order_ID,Customer_ID,Restaurant_Name,City,Cuisine_Type,Dish_Name,Order_Date,Order_Time,Order_Status,Delivery_Duration_Minutes,Payment_Method,Order_Value,Discount_Applied,Customer_Rating,Delivery_Partner_ID,Delivery_Partner_Rating,Cancellation_Reason,Is_First_Order,Restaurant_Rating,Tip_Amount
0,ORD00001,CUST5824,"Becker, Dorsey and Nunez",Bangalore,Chinese,Nature,2024-09-18,18:46:00,Delivered,87.000000,Cash,665.60,Yes,3.100000,DP249,3.2,Not Cancelled,No,4.9,53.12
1,ORD00002,CUST8654,Kim-Hunter,Kolkata,Continental,Evidence,2024-07-02,18:01:41,Delivered,61.000000,UPI,986.56,Yes,2.986572,DP369,NaN,Not Cancelled,Yes,4.8,99.47
2,ORD00003,CUST1015,Powell Inc,Delhi,Chinese,Among,2024-05-21,12:02:54,Cancelled,55.036288,Wallet,799.55,Yes,2.986572,DP569,NaN,Restaurant Unavailable,Yes,3.3,0.00
3,ORD00004,CUST5784,West-Schneider,Kolkata,Thai,He,2025-01-31,02:59:17,Delivered,25.000000,UPI,875.85,No,2.986572,DP295,2.3,Not Cancelled,No,4.1,67.67
4,ORD00005,CUST5540,Patel LLC,Chennai,South Indian,Year,2024-11-02,22:32:50,Delivered,68.000000,Cash,775.78,Yes,4.200000,DP968,4.3,Not Cancelled,No,4.5,35.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,ORD09996,CUST4855,Schwartz-Velez,Chennai,Chinese,Side,2025-04-02,18:55:09,Cancelled,55.036288,UPI,380.59,No,2.986572,DP106,NaN,Customer Cancelled,No,4.9,0.00
9989,ORD09997,CUST3874,"Paul, Johnson and Richardson",Pune,South Indian,Check,2024-09-07,12:45:41,Delivered,81.000000,Card,108.03,Yes,2.900000,DP376,NaN,Not Cancelled,Yes,4.6,66.62
9990,ORD09998,CUST7928,Jackson-Frank,Bangalore,Biryani,While,2025-03-14,18:47:57,Delivered,46.000000,Wallet,736.20,Yes,2.986572,DP585,NaN,Not Cancelled,No,5.0,72.68
9991,ORD09999,CUST4131,Smith Ltd,Kolkata,Continental,Ball,2025-02-01,23:53:14,Cancelled,55.036288,UPI,240.64,Yes,2.986572,DP494,NaN,Other,Yes,3.2,0.00
9992,ORD10000,CUST3804,Downs-Hull,Delhi,Biryani,Cause,2025-03-17,11:47:36,Delivered,65.000000,Wallet,879.02,Yes,4.400000,DP313,3.8,Not Cancelled,Yes,3.0,95.83